name: CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: build and run
      run: bundle exec fastlane build_and_run_tests
      
    - uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
        severity: info
        details: Build succeeded.
        webhookUrl: ${{ secrets.DISCORD }}
  
    - uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        details: Build or Tests fail.
        webhookUrl: ${{ secrets.DISCORD}}
